In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

class CustomRegressionNetwork(nn.Module):
    def __init__(self, architecture, activations):
        super(CustomRegressionNetwork, self).__init__()
        self.layers = len(architecture)
        self.architecture = architecture
        self.activations = activations

        # Define the layers dynamically based on user-provided architecture
        self.fc_layers = nn.ModuleList([nn.Linear(in_features, out_features) for in_features, out_features in zip(architecture[:-1], architecture[1:])])

    def forward(self, x):
        for i in range(self.layers - 2):  # Iterate through hidden layers
            x = self.activations[i](self.fc_layers[i](x))
        x = self.fc_layers[-1](x)  # Output layer (no activation function here)
        return x

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load the California Housing Prices dataset
california_housing = fetch_california_housing()

# Convert data to numeric format
X, y = california_housing.data, california_housing.target

# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [ ]:
# Convert the data to torch tensors
X_train_torch = torch.Tensor(X_train)
y_train_torch = torch.Tensor(y_train)
X_test_torch = torch.Tensor(X_test)
y_test_torch = torch.Tensor(y_test)

In [ ]:
print(X_train_torch.shape)
print(y_train_torch.shape)
print(X_train_torch[0])
print(y_train_torch[0])

torch.Size([16512, 8])
torch.Size([16512, 1])
tensor([-0.3217,  0.3465, -0.1663, -0.1905,  0.7723,  0.0598, -1.3680,  1.2676])
tensor([1.0300])


In [ ]:
architecture = [8, 64, 1]  # User-specified architecture for regression
activations = [torch.relu, torch.relu, lambda x: x]

In [ ]:
# Initialize the neural network with user-provided architecture and activations
net = CustomRegressionNetwork(architecture, activations)

# Define the loss function and optimizer for regression
criterion = nn.MSELoss()  # Mean Squared Error loss for regression
optimizer = optim.SGD(net.parameters(), lr=0.001)

In [ ]:
# Train for 10000 epochs
for epoch in range(2000):
    optimizer.zero_grad()  # Zero the gradients

    outputs = net(X_train_torch)  # Forward pass
    loss = criterion(outputs, y_train_torch)  # Compute the loss
    loss.backward()  # Backpropagation
    optimizer.step()  # Update the weights

    if (epoch+1) % 100 == 0:
        print(f'Epoch [{epoch+1}/2000], Loss: {loss.item():.4f}')


Epoch [100/2000], Loss: 0.6020
Epoch [200/2000], Loss: 0.5970
Epoch [300/2000], Loss: 0.5922
Epoch [400/2000], Loss: 0.5875
Epoch [500/2000], Loss: 0.5830
Epoch [600/2000], Loss: 0.5786
Epoch [700/2000], Loss: 0.5744
Epoch [800/2000], Loss: 0.5703
Epoch [900/2000], Loss: 0.5663
Epoch [1000/2000], Loss: 0.5625
Epoch [1100/2000], Loss: 0.5588
Epoch [1200/2000], Loss: 0.5552
Epoch [1300/2000], Loss: 0.5518
Epoch [1400/2000], Loss: 0.5485
Epoch [1500/2000], Loss: 0.5453
Epoch [1600/2000], Loss: 0.5422
Epoch [1700/2000], Loss: 0.5392
Epoch [1800/2000], Loss: 0.5364
Epoch [1900/2000], Loss: 0.5336
Epoch [2000/2000], Loss: 0.5309


In [ ]:
# Assuming you have your trained model 'net'
with torch.no_grad():
    outputs = net(X_test_torch)  # Get predictions for test data

    # Calculate Mean Squared Error (MSE) for the test data
    test_loss = criterion(outputs, y_test_torch)

print(f'Test Loss: {test_loss.item():.4f}')


Test Loss: 0.5472


In [ ]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch
import torch.nn as nn
import torch.optim as optim

# Load the Wine dataset
wine = load_wine()
X, y = wine.data, wine.target

# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
# Convert the data to torch tensors
X_train_torch = torch.tensor(X_train, dtype=torch.float32)
y_train_torch = torch.tensor(y_train, dtype=torch.long)
X_test_torch = torch.tensor(X_test, dtype=torch.float32)
y_test_torch = torch.tensor(y_test, dtype=torch.long)

In [ ]:
print(X_train_torch.shape)
print(y_train_torch.shape)
print(X_train_torch[0])
print(y_train_torch[0])

torch.Size([142, 13])
torch.Size([142])
tensor([ 1.6545, -0.5892,  1.2190,  1.6531, -0.1223,  0.8090, -0.7221,  1.3549,
         1.9432,  3.4354, -1.6999, -0.9205, -0.2767])
tensor(2)


In [ ]:
# Define the architecture and activations
architecture = [13, 64, 3]  # Input features, hidden layer with 64 neurons, 3 classes for Wine dataset
activations = [torch.relu, torch.relu, nn.Softmax(dim=1)]
# Initialize the neural network with user-provided architecture and activations
net = CustomRegressionNetwork(architecture, activations)


In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001)

In [ ]:
# Train the model for 1000 epochs
for epoch in range(1000):
    optimizer.zero_grad()  # Zero the gradients

    outputs = net(X_train_torch)  # Forward pass
    loss = criterion(outputs, y_train_torch)  # Compute the loss
    loss.backward()  # Backpropagation
    optimizer.step()  # Update the weights

    if (epoch+1) % 100 == 0:
        print(f'Epoch [{epoch+1}/1000], Loss: {loss.item():.4f}')

Epoch [100/1000], Loss: 0.9358
Epoch [200/1000], Loss: 0.8532
Epoch [300/1000], Loss: 0.7817
Epoch [400/1000], Loss: 0.7191
Epoch [500/1000], Loss: 0.6640
Epoch [600/1000], Loss: 0.6149
Epoch [700/1000], Loss: 0.5711
Epoch [800/1000], Loss: 0.5318
Epoch [900/1000], Loss: 0.4964
Epoch [1000/1000], Loss: 0.4645


In [ ]:
# Evaluate the model on the test set
with torch.no_grad():
    outputs = net(X_test_torch)  # Get predictions for test data
    _, predicted = torch.max(outputs, 1)  # Get predicted class labels

    # Calculate accuracy
    correct = (predicted == y_test_torch).sum().item()
    total = y_test_torch.size(0)
    accuracy = correct / total

print(f'Test Accuracy: {100 * accuracy:.2f}%')

Test Accuracy: 97.22%
